language: php

os: linux

dist: bionic

jobs:
    include:
        -   php: '7.4'
            env: SYLIUS_VERSION=1.7.*
        -   php: '7.4'
            env: SYLIUS_VERSION=1.8.*

services:
    - mysql

addons:
    apt:
        sources:
            - google-chrome
        packages:
            - google-chrome-stable
    chrome: stable

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - APP_ENV=test
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"

    - cp -R migrations/* tests/Application/src/Migrations/

install:
    - composer require sylius/sylius:${SYLIUS_VERSION} --no-interaction --no-update
    - |
        if [ $SYLIUS_VERSION = "1.8.*" ]; then
            composer require sylius-labs/doctrine-migrations-extra-bundle --no-interaction --no-update
            cp etc/travis/sylius18/bundles.php tests/Application/config/
            cp etc/travis/sylius18/doctrine_migrations.yaml tests/Application/config/packages/
            cp etc/travis/sylius18/lexik_jwt_authentication.yaml tests/Application/config/packages/
            cp etc/travis/sylius18/security.yaml tests/Application/config/packages/
            cp etc/travis/sylius18/sylius_api.yaml tests/Application/config/routes/
            rm tests/Application/src/Migrations/Version20200604080033.php
        fi
    - composer update --no-interaction --prefer-dist
    - (cd tests/Application && yarn install)

before_script:
    - (cd tests/Application && bin/console doctrine:database:create -vvv)
    - (cd tests/Application && bin/console doctrine:migrations:migrate -n -vvv)
    - (cd tests/Application && bin/console assets:install public -vvv)
    - (cd tests/Application && bin/console cache:warmup -vvv)
    - (cd tests/Application && yarn build)

    - composer link-templates

    # Downloading Symfony CLI
    - |
        if [ ! -f $SYLIUS_CACHE_DIR/symfony ]; then
            wget https://get.symfony.com/cli/installer -O - | bash
            mv ~/.symfony/bin/symfony $SYLIUS_CACHE_DIR
        fi
        php -v | head -n 1 | awk '{ print $2 }' > .php-version

    # Run Chrome Headless
    - google-chrome-stable --enable-automation --disable-background-networking --no-default-browser-check --no-first-run --disable-popup-blocking --disable-default-apps --allow-insecure-localhost --disable-translate --disable-extensions --no-sandbox --enable-features=Metal --headless --remote-debugging-port=9222 --window-size=2880,1800 --proxy-server='direct://' --proxy-bypass-list='*' http://127.0.0.1 > /dev/null 2>&1 &

    # Run webserver
    - (cd tests/Application && $SYLIUS_CACHE_DIR/symfony server:start --port=8080 --dir=public --daemon)

script:
    - composer validate
    - composer analyse

    - vendor/bin/phpunit
    - vendor/bin/phpspec run
    - vendor/bin/behat -vvv --no-interaction || vendor/bin/behat -vvv --no-interaction --rerun

after_failure:
    - vendor/lakion/mink-debug-extension/travis/tools/upload-textfiles "${SYLIUS_BUILD_DIR}/*.log"
