winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                complete_pay_pal_order:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalOrderCompleteProcessor', 'completePayPalOrder']
                    args: ['object']
    sylius_payment:
        callbacks:
            after:
                complete_pay_pal_payment:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalPaymentCompleteProcessor', 'completePayPalPayment']
                    args: ['object']

sylius_order:
    resources:
        order_item:
            classes:
                controller: Sylius\PayPalPlugin\Controller\PayPalOrderItemController
