winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                complete_pay_pal_order:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalOrderCompleteProcessor', 'completePayPalOrder']
                    args: ['object']
    sylius_payment:
        callbacks:
            after:
                complete_pay_pal_payment:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalPaymentCompleteProcessor', 'completePayPalPayment']
                    args: ['object']

sylius_order:
    resources:
        order_item:
            classes:
                controller: Sylius\PayPalPlugin\Controller\PayPalOrderItemController

sylius_grid:
    grids:
        sylius_admin_payment:
            actions:
                main:
                    download_report:
                        type: default
                        label: sylius.pay_pal.download_pay_pal_report
                        icon: download
                        options:
                            link:
                                route: sylius_paypal_plugin_admin_download_payouts_report
