winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                complete_pay_pal_order:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalOrderCompleteProcessor', 'completePayPalOrder']
                    args: ['object']
    sylius_payment:
        callbacks:
            before:
                refund_pay_pal_order:
                    on: ['refund']
                    do: ['@Sylius\PayPalPlugin\Processor\PaymentRefundProcessorInterface', 'refund']
                    args: ['object']
            after:
                complete_pay_pal_payment:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalPaymentCompleteProcessor', 'completePayPalPayment']
                    args: ['object']

sylius_order:
    resources:
        order_item:
            classes:
                controller: Sylius\PayPalPlugin\Controller\PayPalOrderItemController

sylius_grid:
    templates:
        action:
            download_report: "@SyliusPayPalPlugin/Grid/downloadReport.html.twig"
    grids:
        sylius_admin_payment_method:
            actions:
                item:
                    download_report:
                        type: download_report
                        label: sylius.pay_pal.report
                        icon: download
                        options:
                            link:
                                route: sylius_paypal_plugin_admin_download_payouts_report
                                parameters:
                                    id: resource.id

sylius_ui:
    events:
        sylius.shop.product.show.right_sidebar:
            blocks:
                pay_with_pay_pal:
                    template: '@SyliusPayPalPlugin/Buttons/productDetails.html.twig'
                    priority: 7
        sylius.shop.cart.summary:
            blocks:
                pay_with_pay_pal:
                    template: '@SyliusPayPalPlugin/Buttons/cart.html.twig'
                    priority: 7
