winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                complete_pay_pal_order:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalOrderCompleteProcessor', 'completePayPalOrder']
                    args: ['object']
    sylius_payment:
        callbacks:
            after:
                complete_pay_pal_payment:
                    on: ['complete']
                    do: ['@Sylius\PayPalPlugin\Processor\PayPalPaymentCompleteProcessor', 'completePayPalPayment']
                    args: ['object']

sylius_order:
    resources:
        order_item:
            classes:
                controller: Sylius\PayPalPlugin\Controller\PayPalOrderItemController

sylius_grid:
    templates:
        action:
            download_report: "@SyliusPayPalPlugin/Grid/downloadReport.html.twig"
    grids:
        sylius_admin_payment_method:
            actions:
                item:
                    download_report:
                        type: download_report
                        label: sylius.pay_pal.report
                        icon: download
                        options:
                            link:
                                route: sylius_paypal_plugin_admin_download_payouts_report
                                parameters:
                                    id: resource.id
