sylius_paypal_plugin_pay_with_paypal_form:
    path: /pay-with-paypal/{id}
    methods: [GET]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\PayWithPayPalFormAction

sylius_paypal_plugin_create_paypal_order:
    path: /create-pay-pal-order/{token}
    methods: [POST]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\CreatePayPalOrderAction

sylius_paypal_plugin_create_paypal_order_from_cart:
    path: /create-pay-pal-order-from-cart/{id}
    methods: [POST]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\CreatePayPalOrderFromCartAction

sylius_paypal_plugin_complete_paypal_order:
    path: /complete-pay-pal-order/{token}
    methods: [POST]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\CompletePayPalOrderAction

sylius_paypal_plugin_complete_paypal_payment:
    path: /complete-pay-pal-payment/{id}
    methods: [GET]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\CompletePayPalPaymentAction

sylius_paypal_plugin_process_paypal_order:
    path: /process-pay-pal-order/{id}
    methods: [POST]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\ProcessPayPalOrderAction

sylius_paypal_plugin_create_paypal_order_by_id:
    path: /create-pay-pal-order-by-id/{id}
    methods: [POST]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\CreatePayPalOrderByIdAction

sylius_paypal_plugin_complete_paypal_order_by_id:
    path: /complete-pay-pal-order-by-id/{syliusOrderId}/{orderId}
    methods: [POST]
    defaults:
        _controller: Sylius\PayPalPlugin\Controller\CompletePayPalOrderByIdAction
